name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install
              run: npm install

            - name: Test
              run: npm run test:local
            - uses: actions/upload-artifact@v1
              with:
                  name: logs
                  path: logs

            - name: Argos
              continue-on-error: true
              env:
                  ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
              run: npm exec argos upload ./screenshots
